/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import entity.*;
import java.util.Optional;

/**
 *
 * @author Gokhan
 */
public class Main extends javax.swing.JFrame {
    private static MenuItemDAO menuItemDAO;

    public Main() {
        initComponents();
        refreshMenuItemsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtItemDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenuItems = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oaks Donuts");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Item Description");
        jLabel3.setToolTipText("");

        jLabel4.setText("Price");

        tblMenuItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item Name", "Item Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMenuItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenuItems);

        btnInsert.setText("Save");
        btnInsert.addActionListener(evt -> btnInsertActionPerformed(evt));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(evt -> btnUpdateActionPerformed(evt));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(evt -> btnDeleteActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnInsert))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnUpdate))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(txtItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnDelete))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {
        if (!txtID.getText().isEmpty()) {
            try {
                int ID = Integer.parseInt(txtID.getText().trim());
                String name = txtItemName.getText().trim();
                String desc = txtItemDescription.getText().trim();
                double price = Double.parseDouble(txtPrice.getText().trim());
                addMenuItem(ID, name, desc, price);
                refreshMenuItemsTable();
                clearTextFields();
            } catch (NumberFormatException e) {
                alert("Invalid number format for ID or Price", "Insert error");
            }
        } else {
            alert("ID cannot be empty", "Insert error");
        }
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        if (!txtID.getText().isEmpty()) {
            try {
                int ID = Integer.parseInt(txtID.getText().trim());
                String name = txtItemName.getText().trim();
                String desc = txtItemDescription.getText().trim();
                double price = Double.parseDouble(txtPrice.getText().trim());
                MenuItem menuItem = getMenuItem(ID);
                if (menuItem.getID() != -1) {
                    updateMenuItem(ID, name, desc, price);
                    refreshMenuItemsTable();
                } else {
                    alert("Menu Item does not exist", "Update error");
                }
            } catch (NumberFormatException e) {
                alert("Invalid number format for ID or Price", "Update error");
            }
        } else {
            alert("ID cannot be empty", "Update error");
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        if (!txtID.getText().isEmpty()) {
            try {
                int ID = Integer.parseInt(txtID.getText().trim());
                MenuItem menuItem = getMenuItem(ID);
                if (menuItem.getID() != -1) {
                    int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
                    if (option == 0) {
                        deleteMenuItem(ID);
                        refreshMenuItemsTable();
                        clearTextFields();
                    }
                } else {
                    alert("Menu Item does not exist", "Delete error");
                }
            } catch (NumberFormatException e) {
                alert("Invalid number format for ID", "Delete error");
            }
        } else {
            alert("ID cannot be empty", "Delete error");
        }
    }

    private void tblMenuItemsMouseClicked(java.awt.event.MouseEvent evt) {
        int i = tblMenuItems.getSelectedRow();
        TableModel model = tblMenuItems.getModel();
        txtID.setText(model.getValueAt(i, 0).toString());
        txtItemName.setText(model.getValueAt(i, 1).toString());
        txtItemDescription.setText(model.getValueAt(i, 2).toString());
        txtPrice.setText(model.getValueAt(i, 3).toString());
    }

    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
    }

    public void alert(String msg, String title) {
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.ERROR_MESSAGE);
    }

    private static void addMenuItem(int id, String name, String desc, double price) {
        MenuItem menuItem = new MenuItem(id, name, desc, price);
        menuItemDAO.insert(menuItem);
    }

    private static void updateMenuItem(int id, String name, String desc, double price) {
        MenuItem menuItem = new MenuItem(id, name, desc, price);
        menuItemDAO.update(menuItem);
    }

    private static void deleteMenuItem(int id) {
        MenuItem menuItem = new MenuItem(id, "", "", 0.0);
        menuItem.setID(id);
        menuItemDAO.delete(menuItem);
    }

    private static MenuItem getMenuItem(int id) {
        Optional<MenuItem> menuItem = menuItemDAO.get(id);
        return menuItem.orElseGet(() -> new MenuItem(-1, "Non-exist", "Non-exist", 0.0));
    }

    private void clearTextFields() {
        txtID.setText("");
        txtItemName.setText("");
        txtItemDescription.setText("");
        txtPrice.setText("");
    }

    private void refreshMenuItemsTable() {
        List<MenuItem> items = menuItemDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) tblMenuItems.getModel();
        // Clear table
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (MenuItem item : items) {
            Object[] row = new Object[4];
            row[0] = item.getID();
            row[1] = item.getItemName();
            row[2] = item.getItemDescription();
            row[3] = item.getPrice();
            model.addRow(row);
        }
    }

    public static void main(String args[]) {
        menuItemDAO = new MenuItemDAO();
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1, jLabel2, jLabel3, jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMenuItems;
    private javax.swing.JTextField txtID, txtItemName, txtItemDescription, txtPrice;
}